### ISSUE TITLE
Console / Devices search

### ISSUE THREAD

**Issue by slntopp** [infinimesh/infinimesh#565]
Add search to devices page, in github'ish way (to be able to set fields for filtering)
Filter by:

- [ ] UUID
- [ ] Title
- [ ] Tags
- [ ] Namespace
- [ ] Enabled/Disabled state

**Comment by vladimirnikolic509** [comment]
https://github.com/infinimesh/infinimesh/pull/569 @slntopp

**Comment by slntopp** [comment]
- [ ] Devices count is broken (always shows zero)
- [ ] I have all search tokens grayed out, what's the reason

How i've tested:
I've changed `INFINIMESH_VERSION` to `dev` at `.env` file and re-upped the docker compose

![Image](https://github.com/infinimesh/infinimesh/assets/32666515/51bf6359-fd65-4545-8de8-cfdf2ee47cfd)

**Comment by vladimirnikolic509** [comment]
> I have all search tokens grayed out, what's the reason

The reason behind this is, I have disabled the options so that it cannot be selected because when we click that option then it is automatically selected and added as a tag instead of only pasting it on the input field. 

For example: if I click `:uuid:` then it creates a new tag on input field which we don't want. We want to have additional number to be entered after it. So, this is the limitation of the naive ui library itself. May be we can enhance this further making our own custom component but will take time to implement it.  @slntopp

**Comment by slntopp** [comment]
I see.
We should refactor this anyway.

Could you please prepare a proposal for that new component (not the implementation) as the new issue?

Additionally:
 - it should be searching everywhere by default 
 - It should handle the partial data better (for example it doesn't work right with the title currently)

The second issue might not be the part of this search, because we would offload it to backend, so consider using `search_func(search_keys: {}, pool: [])` or smth like that

**Comment by vladimirnikolic509** [comment]
Please check draft: https://github.com/orgs/infinimesh/projects/2/views/3?pane=issue&itemId=51251814 @slntopp

**Comment by slntopp** [comment]
Please fix the device count issue, so we can close this for now
